// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTKHfNBgun7-kNfK2nrsFOD3Caqojo5E',
    appId: '1:42158838434:web:3947fc7c1cc9b5b00d3dfb',
    messagingSenderId: '42158838434',
    projectId: 'menu-digital-2a39e',
    authDomain: 'menu-digital-2a39e.firebaseapp.com',
    databaseURL: 'https://menu-digital-2a39e-default-rtdb.firebaseio.com',
    storageBucket: 'menu-digital-2a39e.appspot.com',
    measurementId: 'G-HPWVEBS0NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ncp6rtKkhcnoFpxPzOIQ9xUkhNBOZIQ',
    appId: '1:42158838434:android:9c8ecb125d01e59e0d3dfb',
    messagingSenderId: '42158838434',
    projectId: 'menu-digital-2a39e',
    databaseURL: 'https://menu-digital-2a39e-default-rtdb.firebaseio.com',
    storageBucket: 'menu-digital-2a39e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtsnvBMaqFwcgQ4Qgq1kudWDetLygCQpw',
    appId: '1:42158838434:ios:4302f2b2c4424ed30d3dfb',
    messagingSenderId: '42158838434',
    projectId: 'menu-digital-2a39e',
    databaseURL: 'https://menu-digital-2a39e-default-rtdb.firebaseio.com',
    storageBucket: 'menu-digital-2a39e.appspot.com',
    iosClientId: '42158838434-5flvmq9d27loppo7jlssvqqdk28cvpan.apps.googleusercontent.com',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtsnvBMaqFwcgQ4Qgq1kudWDetLygCQpw',
    appId: '1:42158838434:ios:4302f2b2c4424ed30d3dfb',
    messagingSenderId: '42158838434',
    projectId: 'menu-digital-2a39e',
    databaseURL: 'https://menu-digital-2a39e-default-rtdb.firebaseio.com',
    storageBucket: 'menu-digital-2a39e.appspot.com',
    iosClientId: '42158838434-5flvmq9d27loppo7jlssvqqdk28cvpan.apps.googleusercontent.com',
    iosBundleId: 'com.example.posApp',
  );
}
